packages:
  - echo-control
  - echo-server
  - echo-typescript-sdk
  - create-echo-app
  - echo-react-sdk
  - integration-tests
  - examples/*
allowBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma
