packages:
  - echo-control
  - echo-server
  - echo-typescript-sdk
  - create-echo-app
  - echo-react-sdk
  - echo-authjs-provider
  - echo-shared-components
  - integration-tests
  - examples/*
allowBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma
ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver
