packages:
  - create-echo-app
  - echo-control
  - echo-server
  - echo-typescript-sdk
  - echo-next-sdk
  - echo-react-sdk
  - echo-authjs-provider
  - integration-tests
  - examples/*
  - smoke/**
allowBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma
ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver
