version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - "${TEST_DB_PORT}:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_DB_USER} -d ${TEST_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  echo-control-test:
    build: 
      context: ../echo-control
      dockerfile: Dockerfile.test
    environment:
      - DATABASE_URL
      - NODE_ENV=test
      - INTEGRATION_TEST_MODE=true
      - CLERK_SECRET_KEY
      - CLERK_PUBLISHABLE_KEY
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
      - JWT_SECRET
      - JWT_ISSUER
      - JWT_AUDIENCE
      - LOG_LEVEL=error
      - DISABLE_RATE_LIMITING=true
      - SKIP_EMAIL_VERIFICATION=true
    ports:
      - "3001:3000"
    depends_on:
      postgres-test:
        condition: service_healthy
    command: |
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 5 &&
        echo 'Running Prisma migrations...' &&
        pnpm prisma:push &&
        echo 'Seeding integration test data...' &&
        INTEGRATION_TEST_MODE=true pnpm prisma db seed &&
        echo 'Starting echo-control in test mode...' &&
        pnpm start
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  playwright:
    image: mcr.microsoft.com/playwright:v1.40.0-focal
    environment:
      - ECHO_CONTROL_URL=http://echo-control-test:3000
      - HEADLESS=true
      - BROWSER_TIMEOUT=30000
    volumes:
      - ../integration-tests:/workspace
    working_dir: /workspace
    depends_on:
      echo-control-test:
        condition: service_healthy
    command: npx playwright test
    profiles:
      - e2e

volumes:
  postgres_test_data: