name: Auto Test Publish

on:
  pull_request:
    paths: ['packages/sdk/**']
  push:
    branches: [master]
    paths: ['packages/sdk/**']

jobs:
  test-publish:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Merit-Systems'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch full history for accurate commit info
          fetch-depth: 0
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Version with commit hash
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_NUM="${{ github.event.number }}"
            PREID="test-pr${PR_NUM}.${SHORT_SHA}"
          else
            PREID="test.${SHORT_SHA}"
          fi
          
          echo "PREID=${PREID}" >> $GITHUB_ENV
          echo "📦 Versioning with preid: ${PREID}"
          
          # Version each package individually with the preid
          pnpm --filter @merit-systems/echo-typescript-sdk version prerelease --preid="${PREID}"
          pnpm --filter @merit-systems/echo-react-sdk version prerelease --preid="${PREID}"
          pnpm --filter @merit-systems/echo-next-sdk version prerelease --preid="${PREID}"
          pnpm --filter echo-start version prerelease --preid="${PREID}"
      
      - name: Build packages
        run: pnpm run build
      
      - name: Publish to test tag
        run: pnpm run publish:sdks:test-live
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Get package version
        id: version
        run: |
          VERSION=$(node -p "require('./packages/sdk/ts/package.json').version")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      
      - name: Comment PR with test instructions
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const version = '${{ steps.version.outputs.version }}';
            const preid = process.env.PREID;
            
            const comment = `🧪 **Test Version Published**
            
            Install this PR's test version:
            \`\`\`bash
            npm install @merit-systems/echo-typescript-sdk@test
            # or specific version:
            npm install @merit-systems/echo-typescript-sdk@${version}
            \`\`\`
            
            This version includes the bundled AI SDK packages to test our version conflict fixes.
            
            **Test checklist:**
            - [ ] Authentication works correctly
            - [ ] No separate @ai-sdk/openai packages in node_modules
            - [ ] Echo token injection works as expected
            
            _Version: \`${version}\` (commit: \`${process.env.GITHUB_SHA.substring(0, 7)}\`)_`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
      
      - name: Summary
        run: |
          echo "✅ Test version published successfully!"
          echo "📦 Version: ${{ steps.version.outputs.version }}"
          echo "🏷️  Tag: test"
          echo ""
          echo "Install with: npm install @merit-systems/echo-typescript-sdk@test"