name: CI Checks

on:
  pull_request:
    branches: [master]
    paths:
      - 'packages/app/control/**'
      - '.github/workflows/ci-checks.yml'

jobs:
  ci-checks:
    name: Run CI Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install workspace dependencies
        run: pnpm install --frozen-lockfile

      - name: Run CI checks
        working-directory: ./packages/app/control
        run: pnpm run ci-checks
